datasets:
  - id: "novelty"
    format: "mat"
    path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/EpochedData/Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV4.mat"
  - id: "complexity_rest"
    format: "mat_cell"
    path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/Complexity/complexitySampeEnStandardizeChBaselineSessions.mat"


preprocessors:
  - id: "selectsession"
    name: "selectsession"
    args:
      session_indexs: [0,9,10,11,12,13,14,15,16,17,18,19,20,21]
  - id: "zscore_norm"
    name: "zscore"
    args: {dim: -1}

features:
  - id: "ccdfc_novelty"
    name: "cross-correlation-di-fc"
    dataset: "novelty"
    preprocessors: ["selectsession"]
    args:
      fs: 2000
      channel_pairs: [[0,2],[3,2]]
      band: [8,12] # Theta band
      time_window: [1340,1740]

visualizers:
  - name: "trial_dynamic_feature_visualizer"
    args: 
      FeatureName: "Complexity"
      legends: ["CA1-Striatum","PFC-Striatum"]
    inputs:
      - feature: "ccdfc_novelty"
