datasets:
  - id: "novelty"
    format: "mat_events"
    path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/EpochedData/Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV3.mat"
  - id: "complexity_rest"
    format: "mat_cell"
    path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/Complexity/complexitySampeEnStandardizeChBaselineSessions.mat"


preprocessors:
  - id: "selectsession"
    name: "selectsession"
    args:
      session_indexs: [8,10]
      # session_indexs: [8,10,16,17,27,28,29,30,0,1,2,3,4,5,6,7]
  - id: "zscore_norm"
    name: "zscore"
    args: {dim: -1}

features:
  - id: "TimeTrial"
    name: "TimeTrial"
    dataset: "novelty"
    preprocessors: ["selectsession","zscore_norm"]
    args:
      feature_name: "Complexity_base"
      window_size: 400
      overlap: 0.5
      feature_args:
        complexity_type: "SampEn"
        arguments: 
            m: 2
            r: 0.15
            tau: 1


storages:
  - name: "mat"
    args: 
      TimeTrial:
          path: "/home/mohammad/Desktop/PiplineCodes/Complexity/TimeTrialComplexity2.mat"
          variable_name: "TimeTrial_Complexity" # for mat storage, this item is manditory 
