datasets:
  - id: "novelty"
    format: "mat_events"
    path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/EpochedData/Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV3.mat"
  - id: "complexity_rest"
    format: "mat_cell"
    path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/Complexity/complexitySampeEnStandardizeChBaselineSessions.mat"


preprocessors:
  - id: "selectsession"
    name: "selectsession"
    args:
      session_indexs: [8,10,16,17,27,28,29,30,0,1,2,3,4,5,6,7]
  - id: "zscore_norm"
    name: "zscore"
    args: {dim: -1}

features:
  - id: "ERP_Target"
    name: "EventERP"
    dataset: "novelty"
    preprocessors: ["zscore_norm"]
    args:
      event_type: 2
      channels: [0]
  - id: "ERP_Standard"
    name: "EventERP"
    dataset: "novelty"
    preprocessors: ["zscore_norm"]
    args:
      event_type: 1
      channels: [0]

visualizers:
  - name: "time_dynamic_feature_visualizer"
    args: 
      FeatureName: "Complexity"
      legends: ["CA1"]
      xrange: [-0.47,1.27]
      scheme: "same_figure"
    inputs:
      - feature: "ERP_Target"
      - feature: "ERP_Standard"
