dataset:
  format: "mat"
  path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/EpochedData/Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV3.mat"

features:
  - name: TE
    args:
      d_x: 5
      d_y: 1
      w_x: 10
      w_y: 10
      channel_pairs: [[1,2],[2,3]]
      time_window: [1340,1740]


visualizers:
  - name: "trial_dyanmic_feature_visualizer"
    args:
      arguments:
        FeatureName: TE
        legends: ["ch1-2","ch2-3"]

