datasets:
  - id: "novelty"
    format: "mat_events"
    path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/EpochedData/Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV3.mat"
  - id: "complexity_rest"
    format: "mat_cell"
    path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/Complexity/complexitySampeEnStandardizeChBaselineSessions.mat"


preprocessors:
  - id: "selectsession"
    name: "selectsession"
    args:
      session_indexs: [8,10]
      # session_indexs: [8,10,16,17,27,28,29,30,0,1,2,3,4,5,6,7]
  - id: "zscore_norm"
    name: "zscore"
    args: {dim: -1}

features:
  - id: "TimeTrial"
    name: "TimeTrialPair"
    dataset: "novelty"
    preprocessors: ["selectsession","zscore_norm"]
    args:
      feature_name: "TE_base" # For TimeTrialPair Feature you need to use the base features that work with two window, e.g. functional connectivity features
      window_size: 400
      channel_pairs: [[0,1],[2,3],[0,3]]  # Example channel pairs
      overlap: 0.5
      feature_args:
        d_x: 1
        d_y: 1
        w_x: 15
        w_y: 15



storages:
  - name: "mat"
    args: 
      TimeTrial:
          path: "/home/mohammad/Desktop/PiplineCodes/FunctionalConnectivities/TimeTrialTE1.mat"
          variable_name: "TimeTrial_TE" # for mat storage, this item is manditory 