dataset:
  format: "mat"
  path: "D:\\D\\ComplexityCheckCodes\\RawData\\PiplineCodes\\EpochedData\\Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV4.mat"
  # path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/EpochedData/Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV3.mat"

preprocessors:
  - name: "selectsession"
    args:
      session_indexs: [9,10,11,12,13,14,15,16,17,18,19,20]

features:
  - name: DPLI
    args:
      sfreq: 2000
      x_lowcut: 5
      x_highcut: 8
      y_lowcut: 5
      y_highcut: 8
      channel_pairs: [[1,2],[2,3]]
      time_window: [400,600]

visualizers:
  - name: "trial_dyanmic_feature_visualizer"
    args:
      arguments:
        FeatureName: DPLI
        legends: ["ch1-2","ch2-3"]