dataset:
  format: "mat"
  path: "D:\\D\\ComplexityCheckCodes\\RawData\\PiplineCodes\\EpochedData\\Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV3.mat"
  # path: "/media/mohammad/atp/D/ComplexityCheckCodes/RawData/PiplineCodes/EpochedData/Fix_Ch_Order_PreConfig_1_epoched_preprocessed_novelty0-raw_dataV3.mat"

preprocessors:
  - name: "selectsession"
    args:
      session_indexs: [8,9,10,11,12,13,14,15,16,17,18,19]  
  - name: "zscore"
    args:
      dim: -1  # Z-score normalization across the last dimension (time)
features:
  - name: Complexity
    args:
      complexity_type: "SampEn"
      arguments: 
        m: 2
        r: 0.15
        tau: 1
      channels: [0,1,2,3]
      time_window: [1340,1740]


visualizers:
  - name: "trial_dyanmic_feature_visualizer"
    args:
      arguments:
        FeatureName: TE
        legends: ["CA1","Thalamus","Striatum","PFC"]
